# Generated by Django 5.2.8 on 2025-11-12 18:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อสนาม')),
                ('sport_type', models.CharField(choices=[('football', 'ฟุตบอล'), ('futsal', 'ฟุตซอล'), ('basketball', 'บาสเกตบอล'), ('volleyball', 'วอลเลย์บอล'), ('badminton', 'แบดมินตัน'), ('tennis', 'เทนนิส')], max_length=20, verbose_name='ประเภทกีฬา')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='ความจุ (คน)')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ราคา/ชม.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sport_fields/', verbose_name='รูปภาพ')),
                ('status', models.CharField(choices=[('available', 'พร้อมใช้งาน'), ('maintenance', 'ปิดปรับปรุง')], default='available', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'สนามกีฬา',
                'verbose_name_plural': 'สนามกีฬา',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('role', models.CharField(choices=[('user', 'ผู้ใช้ทั่วไป'), ('admin', 'ผู้ดูแลระบบ')], default='user', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sport_fields/', verbose_name='รูปภาพ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='วันที่จอง')),
                ('start_time', models.TimeField(verbose_name='เวลาเริ่มต้น')),
                ('end_time', models.TimeField(verbose_name='เวลาสิ้นสุด')),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='จำนวนชั่วโมง')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคารวม')),
                ('status', models.CharField(choices=[('pending', 'รอยืนยัน'), ('confirmed', 'ยืนยันแล้ว'), ('cancelled', 'ยกเลิก'), ('completed', 'เสร็จสิ้น')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จอง')),
                ('sport_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.sportfield', verbose_name='สนาม')),
            ],
            options={
                'verbose_name': 'การจอง',
                'verbose_name_plural': 'การจอง',
                'ordering': ['-booking_date', '-start_time'],
            },
        ),
    ]
